containers:
- name: oauth2-proxy
  image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.3
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      cpu: 10m
      memory: 20Mi
