# permissions for end users to view configurationoverlays.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configurationoverlay-viewer-role
rules:
- apiGroups:
  - platform.plural.sh
  resources:
  - configurationoverlays
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.plural.sh
  resources:
  - configurationoverlays/status
  verbs:
  - get
