# permissions for end users to view defaultstorageclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: defaultstorageclass-viewer-role
rules:
- apiGroups:
  - plaform.plural.sh.plural.sh
  resources:
  - defaultstorageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - plaform.plural.sh.plural.sh
  resources:
  - defaultstorageclasses/status
  verbs:
  - get
