# permissions for end users to view logfilters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logfilter-viewer-role
rules:
- apiGroups:
  - platform.plural.sh
  resources:
  - logfilters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.plural.sh
  resources:
  - logfilters/status
  verbs:
  - get
