# permissions for end users to edit logfilters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logfilter-editor-role
rules:
- apiGroups:
  - platform.plural.sh
  resources:
  - logfilters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.plural.sh
  resources:
  - logfilters/status
  verbs:
  - get
