# permissions for end users to edit logtails.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logtail-editor-role
rules:
- apiGroups:
  - platform.plural.sh
  resources:
  - logtails
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.plural.sh
  resources:
  - logtails/status
  verbs:
  - get
