# permissions for end users to edit proxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxy-editor-role
rules:
- apiGroups:
  - platform.plural.sh
  resources:
  - proxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.plural.sh
  resources:
  - proxies/status
  verbs:
  - get
