# permissions for end users to edit resourcegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resourcegroup-editor-role
rules:
- apiGroups:
  - platform.plural.sh
  resources:
  - resourcegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.plural.sh
  resources:
  - resourcegroups/status
  verbs:
  - get
