---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - platform.plural.sh
  resources:
  - resourcegroups
  verbs:
  - get
  - list
  - watch
