
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - update
- apiGroups:
  - plaform.plural.sh.plural.sh
  resources:
  - defaultstorageclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - plaform.plural.sh.plural.sh
  resources:
  - defaultstorageclasses/finalizers
  verbs:
  - update
- apiGroups:
  - plaform.plural.sh.plural.sh
  resources:
  - defaultstorageclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - platform.plural.sh
  resources:
  - licenses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.plural.sh
  resources:
  - licenses/finalizers
  verbs:
  - update
- apiGroups:
  - platform.plural.sh
  resources:
  - licenses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - platform.plural.sh
  resources:
  - resourcegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.plural.sh
  resources:
  - secretsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.plural.sh
  resources:
  - secretsyncs/finalizers
  verbs:
  - update
- apiGroups:
  - platform.plural.sh
  resources:
  - secretsyncs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - platform.plural.sh
  resources:
  - statefulsetresizes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.plural.sh
  resources:
  - statefulsetresizes/finalizers
  verbs:
  - update
- apiGroups:
  - platform.plural.sh
  resources:
  - statefulsetresizes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - patch
  - update
  - watch
