# permissions for end users to view runbooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runbook-viewer-role
rules:
- apiGroups:
  - platform.plural.sh
  resources:
  - runbooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.plural.sh
  resources:
  - runbooks/status
  verbs:
  - get
