# permissions for end users to edit runbooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runbook-editor-role
rules:
- apiGroups:
  - platform.plural.sh
  resources:
  - runbooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.plural.sh
  resources:
  - runbooks/status
  verbs:
  - get
