# permissions for end users to edit secretsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretsync-editor-role
rules:
- apiGroups:
  - platform.plural.sh
  resources:
  - secretsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.plural.sh
  resources:
  - secretsyncs/status
  verbs:
  - get
