# permissions for end users to edit slashcommands.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slashcommand-editor-role
rules:
- apiGroups:
  - platform.plural.sh
  resources:
  - slashcommands
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.plural.sh
  resources:
  - slashcommands/status
  verbs:
  - get
