# permissions for end users to view slashcommands.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slashcommand-viewer-role
rules:
- apiGroups:
  - platform.plural.sh
  resources:
  - slashcommands
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.plural.sh
  resources:
  - slashcommands/status
  verbs:
  - get
