# permissions for end users to edit statefulsetresizes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: statefulsetresize-editor-role
rules:
- apiGroups:
  - platform.plural.sh
  resources:
  - statefulsetresizes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.plural.sh
  resources:
  - statefulsetresizes/status
  verbs:
  - get
