# permissions for end users to view statefulsetresizes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: statefulsetresize-viewer-role
rules:
- apiGroups:
  - platform.plural.sh
  resources:
  - statefulsetresizes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.plural.sh
  resources:
  - statefulsetresizes/status
  verbs:
  - get
