# permissions for end users to view wireguards.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wireguard-viewer-role
rules:
- apiGroups:
  - vpn.plural.sh
  resources:
  - wireguards
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vpn.plural.sh
  resources:
  - wireguards/status
  verbs:
  - get
