# permissions for end users to edit wireguardpeers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wireguardpeer-editor-role
rules:
- apiGroups:
  - vpn.plural.sh
  resources:
  - wireguardpeers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vpn.plural.sh
  resources:
  - wireguardpeers/status
  verbs:
  - get
