apiVersion: vpn.plural.sh/v1alpha1
kind: WireguardServer
metadata:
  name: wireguardserver-sample
  namespace: default
spec:
  serviceType: LoadBalancer
  wireguardImage: dkr.plural.sh/bootstrap/wireguard-server:0.1.2
  networkCIDR: 10.8.0.1/24
  mtu: "8921"
  dns:
  - "1.1.1.1"
  - "8.8.8.8"
  allowedIPs:
  - "0.0.0.0/0"
  enableHA: true
  resources:
    limits:
      # cpu: 90m # 1 client with a 4k youtube stream uses ~ 90m cpu, but since cpu limits in K8s are an anti-pattern it isn't set
      memory: 128Mi
    requests:
      cpu: 15m
      memory: 32Mi
  serviceAnnotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: HTTP
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "9586"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/metrics"
