apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- name: moauthinjector.security.plural.sh
  objectSelector:
    matchExpressions:
    - key: security.plural.sh/inject-oauth-sidecar
      operator: In
      values:
      - "true"
