apiVersion: v1
kind: ConfigMap
metadata:
  name: plural-operator-oauth-sidecar-config
data:
  oauth-sidecar-config.yaml: |
    containers:
    - name: oauth2-proxy
      image: dkr.plural.sh/oauth2-proxy/oauth2-proxy/oauth2-proxy:v7.3.0
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 25m
          memory: 50Mi
        limits:
          memory: 50Mi
      ports:
      - name: oauth-http
        containerPort: 4180
        protocol: TCP
      - name: oauth-metrics
        containerPort: 44180
        protocol: TCP
