# permissions for end users to edit secretsyncs.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plural-operator
  labels:
  {{ include "plural-operator.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plural-operator-role
  labels:
  {{ include "plural-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - platform.plural.sh
  - apps
  resources:
  - secretsyncs
  - secrets
  - runbooks
  - statefulsetresizes
  - persistentvolumeclaims
  - statefulsets
  - defaultstorageclasses
  - resourcegroups
  - licenses
  - registrycredentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.plural.sh
  resources:
  - secretsyncs/status
  - runbooks/status
  - licenses/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - watch
  - list
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - watch
  - list
  - delete
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - watch
  - list
  - update
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
  - delete
- apiGroups:
  - vpn.plural.sh
  resources:
  - wireguardpeers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vpn.plural.sh
  resources:
  - wireguardpeers/finalizers
  verbs:
  - update
- apiGroups:
  - vpn.plural.sh
  resources:
  - wireguardpeers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vpn.plural.sh
  resources:
  - wireguardservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vpn.plural.sh
  resources:
  - wireguardservers/finalizers
  verbs:
  - update
- apiGroups:
  - vpn.plural.sh
  resources:
  - wireguardservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-election-role
  labels:
  {{ include "plural-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - configmaps
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: plrl-operator-rolebinding
  labels:
  {{ include "plural-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: plural-operator-role
subjects:
- kind: ServiceAccount
  name: plural-operator
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: plrl-operator-leader-election-rolebinding
  labels:
  {{ include "plural-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
- kind: ServiceAccount
  name: plural-operator
