apiVersion: v1
kind: Service
metadata:
  name: plural-operator
  labels:
{{ include "plural-operator.labels" . | indent 4 }}
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    control-plane: plural-operator
---
apiVersion: v1
kind: Service
metadata:
  name: plural-operator-webhook-service
spec:
  ports:
  - port: 443
    targetPort: webhook-server
    protocol: TCP
    name: https-webhook-server
  selector:
    control-plane: plural-operator
