# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/platform.plural.sh_dashboards.yaml
- bases/platform.plural.sh_logfilters.yaml
- bases/platform.plural.sh_proxies.yaml
- bases/platform.plural.sh_slashcommands.yaml
- bases/platform.plural.sh_secretsyncs.yaml
- bases/platform.plural.sh_runbooks.yaml
- bases/platform.plural.sh_statefulsetresizes.yaml
- bases/platform.plural.sh_defaultstorageclasses.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesJson6902:
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: defaultstorageclasses.platform.plural.sh
    path: patches/defauflstorageclass_singleton.yaml

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_dashboards.yaml
#- patches/webhook_in_logfilters.yaml
#- patches/webhook_in_proxies.yaml
#- patches/webhook_in_slashcommands.yaml
#- patches/webhook_in_secretsyncs.yaml
#- patches/webhook_in_runbooks.yaml
#- patches/webhook_in_statefulsetresizes.yaml
#- patches/webhook_in_defaultstorageclasses.yaml
# - patches/defauflstorageclass_singleton.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_dashboards.yaml
#- patches/cainjection_in_logfilters.yaml
#- patches/cainjection_in_proxies.yaml
#- patches/cainjection_in_slashcommands.yaml
#- patches/cainjection_in_secretsyncs.yaml
#- patches/cainjection_in_runbooks.yaml
#- patches/cainjection_in_statefulsetresizes.yaml
#- patches/cainjection_in_defaultstorageclasses.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
