name: Helm
on:
  push:
    branches:
    - main
jobs:
  publish:
    name: Publish chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Setup Helm
        uses: azure/setup-helm@v3
      - name: Run chart-releaser
        id: release
        uses: helm/chart-releaser-action@v1.6.0
        with:
          config: "./.github/configs/cr.yaml"
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
